#!/bin/bash
#SBATCH --job-name=moco_mmt
#SBATCH --account=ub62
#SBATCH --gres=gpu:V100:1
#SBATCH --partition=m3g
#SBATCH --ntasks=1
#SBATCH --time=168:00:00
#SBATCH --mem-per-cpu=16384

module load cuda
python main_moco.py --job_name mmt99 --batch-size 128 --lr 0.03 --moco-m 0.99 --epochs 200 2>&1 | tee logs/mmt99.txt
python main_moco.py --job_name mmt9 --batch-size 128 --lr 0.03 --moco-m 0.9 --epochs 200 2>&1 | tee logs/mmt9.txt